server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newDB
    username: postgres
    password: nisarg@0926
    driver-class-name: org.postgresql.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: YourSecretKeyMustBeVeryLongAndSecureToAvoidThisError12345678
  expiration: 86400000 